apiVersion: v1
kind: Service
metadata:
  name: flask-blue
  annotations:
    cloud.google.com/neg: '{"exposed_ports": {"80":{"name": "flask-blue-service-80-neg"}}}'
  labels:
    app: flask-blue
    tier: web
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: flask-blue
    tier: web
